### ISSUE TITLE
FormatMesage component bag

### ISSUE THREAD

**Issue by maystrenkoYurii** [formatjs/react-intl#1331] opened 2019-06-19 19:15 UTC
Not work this code `<FormattedMessage
          id="app.page.footer.about.description"
          values={{
            app: <b className="footer-about_text_app">{constants.APP_NAME}</b>,
          }}
        >
          {text => <span className="footer-about_text">{text}</span>}
        </FormattedMessage>`

returned only app values in text to span, without other text.
"app.page.footer.about.description": "{app} - is an online...."

**Comment by longlho** [comment] 2019-06-19 19:17
I'm not sure I understand the issue. Can you make a quick codesandbox demo or such?

**Comment by maystrenkoYurii** [comment] 2019-06-19 19:20
@longlho 
![Снимок](https://user-images.githubusercontent.com/23016311/59793913-60732800-92e0-11e9-9551-4b5b0f05c865.PNG)
function text retutned onli app value, withot text "app.page.footer.about.description": "{app} - is an online...."

**Comment by maystrenkoYurii** [comment] 2019-06-19 19:28
@longlho this version code without html tag b good work
![Снимок](https://user-images.githubusercontent.com/23016311/59794291-5271d700-92e1-11e9-8c78-84b2075941f0.PNG) but a have created StudyDiary word with bold style

**Comment by longlho** [comment] 2019-06-19 19:31
I think this is a duplicate of #1255

**Comment by maystrenkoYurii** [comment] 2019-06-19 19:32
@longlho no

**Comment by maystrenkoYurii** [comment] 2019-06-19 20:02
@longlho ??

**Comment by longlho** [comment] 2019-06-19 20:06
if the token is a react element, the children fn will take in an array of chunks as the arguments, e.g: `<FormattedMessage>{(...chunks) => <span>{chunks}</span>}</FormattedMessage>` is prob what u want

**Comment by maystrenkoYurii** [comment] 2019-06-20 17:26
thanks this work

**Closed** 2019-06-20 18:48 UTC

**Comment by DragonRaider5** [comment] 2019-06-20 19:17
See #1204
