### ISSUE TITLE
The introduction of react-intl caused some model pages to crash

### ISSUE THREAD

**Issue by mtsee** [formatjs/react-intl#1582] opened 2020-02-17 08:58 UTC
After using this method, it will lead to accidental flash back or death of some models' pages. Use WeChat built-in browser or alipay's built-in browser to open the page.Examples: oppo r9, huawei P30, huawei mate20 and many other models.

使用该方法后，会导致部分机型页面偶然性的闪退或者死掉，使用微信内置浏览器，或者支付宝的内置浏览器打开页面。举例：oppo r9 ，华为P30，华为mate20等很多机型。

**Comment by longlho** [comment] 2020-02-18 00:04
dupe of https://github.com/formatjs/react-intl/issues/1518

**Closed by longlho** 2020-02-18 00:04 UTC
Labels: bug
