### ISSUE TITLE
RichText: Each child in a list should have a unique "key"

### ISSUE THREAD

**Issue by HollyPony** [formatjs/react-intl#1467] opened 2019-09-02 11:41 UTC
# Expected behavior

No error using the documentation sample for `useIntl().formatMessage`

### Current behavior

Errors about child unique keys from react.

### Step to reproduce for BUG REPORT

https://codesandbox.io/s/formatjsreact-intlissues1359-fftes 

### Your Environment

- react 16.9
- react-intl 3.1.12
- npm / node from `codesandbox` versions

Reproducing in latest chrome / firefox osx versions.

**Comment by longlho** [comment] 2019-09-03 02:37
I'm afraid this is not something we can fix without cloning the React element supplied as values, which incurs overhead. The reason is that since it produces an array of mixed string & `ReactElement`, React complains that there's missing keys

**Comment by HollyPony** [comment] 2019-09-04 12:38
That's embarassing 🤔 

Could you provide me which files are concerned ? Maybe I can help, or ask react team ?

**Comment by longlho** [comment] 2019-09-08 04:09
So this is where we render the formatted tag: https://github.com/formatjs/formatjs/blob/master/packages/intl-messageformat/src/formatters.ts#L406

**Comment by HollyPony** [comment] 2019-09-11 10:15
I have no time for now but for tracking purposes since the related master file has changed I reference the original one : https://github.com/formatjs/formatjs/blob/7e72fee44fd12ad3816b8a0958a66dcfd3a13927/packages/intl-messageformat/src/formatters.ts#L406

+ the new master : https://github.com/formatjs/formatjs/blob/master/packages/intl-messageformat/src/formatters.ts#L337

**Comment by richworx** [comment] 2019-10-18 18:23
This is a problem for me also. I have worked around it using the following hack:

1. Define a counter variable (usually locally scoped near the place FormatMessage is used)
2. Each formatting function (like `bold`) increments the counter and uses it as the key.

For example, in the OP's codesandbox example, just define this above the call to `render`:
```jsx
let tagIndex = 0;
const bold = (...str) => (<strong key={++tagIndex}>{str}</strong>);
```
and later pass that instance of `bold` to `FormatMessage` (or in this case, `RichText`):
```jsx
<RichText id="testCase" values={{bold}} />
```

This avoids the warnings, but is obviously not a great solution, due to the need to create the counter variables and to ensure that they are locally scoped to each usage of FormatMessage.

Here is a more complete example, where the counter is defined locally to the RichText component, so it won't be shared across RichText instances.

https://codesandbox.io/embed/formatjsreact-intlissues1359-ukzz9

I have to look into this more, but perhaps a solution might be to wrap each element in a Fragment before returning the array in *formatjs/packages/intl-messageformat/src/formatters.ts*
```jsx
let tagIndex = 0;
const wrapFragment = (part) => (<Fragment key={++tagIndex}>{part}</Fragment>);
return [`<${tagName}>`, ...chunks.map(wrapFragment), `</${tagName}>`];
```

**Comment by mbalaam** [comment] 2019-11-13 09:55
Until someone designs a better solution this is what I have found works OK for now.

````
chunks.map((chunk, i) => (
  <React.Fragment key={i}>{chunk}</React.Fragment>
))
````

**Comment by longlho** [comment] 2019-11-13 13:41
Yeah that would be what I recommend. If I were to fix it that'd also be what I'd do. The chunks we return can be text and/or React chunks so the other way is that we have to clone them & add `key`, which has performance implication. I'll update the documentation to link to this issue & close it afterwards. Thanks @richworx @mbalaam

**Closed** 2019-11-13 14:20 UTC

**Comment by czabaj** [comment] 2020-04-03 15:21
What about using [Children.toArray](https://reactjs.org/docs/react-api.html#reactchildrentoarray), this is IMHO the simplest way how to solve unique keys when rendering array.

```javascript
(...chunks) => <Component>{React.Children.toArray(chunks)}</Component>
```

😉

**Comment by mbalaam** [comment] 2020-04-03 16:17
Ah, good knowledge! I’d not come across that method before.

**Comment by czabaj** [comment] 2020-04-04 17:40
@richworx I've never done benchmark of `React.children.toArray`, I checked the source code and it [calls `cloneAndReplaceKeys`](https://github.com/facebook/react/blob/c083a643b1539b4d874895fabc19a34ecd2831ed/packages/react/src/ReactChildren.js#L122) so its performance might be close to `React.cloneElement()`, but without real world benchmark, who knows? And simplification of code for users is worth some CPU cycles, unless practice proves different.

From my point of view, library shall take care about unique ids. I saw flag in source code with name [`wrapRichTextChunksInFragment`](https://github.com/formatjs/react-intl/blob/a914dc059cc8d0c04baec6a63513cb686ff6dad3/src/formatters/message.ts#L111), it seems that somebody shares my opinion, am I right?

Also, I think that passing single argument `ReactNode` into `FormatXMLElementFn ` will be better API. The library can then perform check for number of chunks and return first node when `chunks.length === 1`. Also, there is some penalty when transpiling rest operator to ES5 and overall the rationale behind the rest operator in `FormatXMLElementFn` is IMHO hard to explain.

@longlho I will create PR happily, but there seems to effort to handle unique ids in library, see 2nd paragraph.

**Comment by longlho** [comment] 2020-04-05 01:34
yeah there's a config that u can use to do turn that on. Regarding performance, none of it makes any difference in the real world unless you're re-rendering multiple times per second (like in a finance app). When you're in that scenario even using React at all is a decision that should be revisited (and use the imperative API instead).

**Comment by czabaj** [comment] 2020-04-05 16:36
In `formatMessage()` imperative API docs, in example of rich text, there is no rest operator in `FormatXMLElementFn`, [see the docs](https://github.com/formatjs/react-intl/blob/master/docs/API.md#formatmessage) and scroll to rich text example.

The `wrapRichTextChunksInFragment` config option is redundant in Component API, because it wraps the result of `formatMessage()` call in `<React.Fragment>`, whilst in Component API, the result of `formatMessage()` call is wrapped in some kind of component by design.

I don't understand where it makes sense to use rest operator. Maybe when one uses nested rich texts

```JSX
<FormatMessage
  defaultMessage="This is <b>an example <i>of nested</i> rich texts</b>."
  values={{
    b: (...chunks) => <b>{React.Children.toArray(chunks)}</b>, // spread operator maybe needed?
    i: (chunk) => <i>{chunk}</i> // spread not needed
  }}
/>
```

Is nested rich texts even supported? If not, the inside of xml markup could be concatenated as string. If so, why don't use concatenation like this

```JavaScript
const mergedParts = parts.some(isReactNode)
  ? React.Childre.toArray(parts)
  : parts.join('')
formatFn(mergedParts)
```

If I would have some time tomorrow, I will write more tests to investigate how this works. Meantime, any explanation will be welcoming.

**Comment by longlho** [comment] 2020-04-05 16:54
Nested rich text is supported

**Comment by HollyPony** [comment] 2020-04-05 18:29
I wonder if there a reason to not use the `toMap` syntax ?

```javascript
b: (...chunks) => React.Children.toMap(chunks, chunk => <b>{chunk}</b>)
```

That sound more consistent for me. But I should miss something

**Comment by czabaj** [comment] 2020-04-07 06:22
@HollyPony the example with `toMap` wraps each and every chunk in React component, but you typically want to wrap all chunks in single React component.

@longlho as for my investigation, these parts of documentation regards rich text formatting
1. [Components](https://github.com/formatjs/react-intl/blob/master/docs/Components.md#rich-text-formatting) are the only one mentioning unique "key" problem and in Caveats section links to
1. [intl-messageformat](https://github.com/formatjs/formatjs/tree/master/packages/intl-messageformat#caveats) which is different, UI agnostic package, but it uses React-like example and spread is not used for `formatXMLElementFn`,
1. [API](https://github.com/formatjs/react-intl/blob/master/docs/API.md#formatmessage) which does not use spread and does not mention any caveats,

I think that documenting the unique "key" problem would be best in the caveats section of [intl-messageformat](https://github.com/formatjs/formatjs/tree/master/packages/intl-messageformat#caveats) and link from other parts of documentation to it.

But I also think we could be able to solve this problem once for all in `react-intl` library

```JavaScript
const mergeChunks = chunks => chunks.length < 2 ? chunks[0] : React.Children.toArray(chunks)

// create high order formatXMLElementFn so formatXMLElementFn then don't need spread
const patchXMLElementFn = formatXMLElementFn =>
    chunks => formatXMLElementFn(mergeChunks(chunks))

// and patch all formatXMLElementFn in values.
const patchedValues = values.map(v => isFunction(v) ? patchFormatXMLElementFn(v) : v)
```

somewhere here https://github.com/formatjs/react-intl/blob/master/src/formatters/message.ts#L134
and library maintainer will surely find a better way to do this. Or _is there any reason to keep chunks as an array and spread them into formatXMLElementFn in variadic fashion?_ Current API causes users many problems and AFAIK does not bring any advantage at all.

**Comment by richworx** [comment] 2020-04-07 18:35
@czabaj I think it's safest to keep chunks  as rest parameter, i.e. `(...chunks)`, because if you pass in an array instead, then all code like you gave in your example will receive `...chunks` as  `ReactNode[][]` (an array of arrays). This would be a breaking change if someone uses code like HollyPony gave: `b: (...chunks) => React.Children.toMap(chunks, chunk => <b>{chunk}</b>)`.

I agree with you that code like that is probably not very common, but even if no one has code like that, it will still be a breaking change with respect to `TypeScript` because the `chunks` parameter changes from `ReactNode[]` to `ReactNode[][]`.

```jsx
// Old version:
(...chunks: ReactNode[] ) => <Component>{chunks}</Component>

// New version:
(...chunks: ReactNode[][]) => <Component>{chunks}</Component>
or
(chunks: ReactNode[]) => <Component>{chunks}</Component>
```
Whichever "new version" the developer chooses, it will require code changes.

**Comment by longlho** [comment] 2020-04-07 21:40
@czabaj can you clarify on the issues? If it's the `missing key` issue you'd still have it regardless of whether the function is variadic or not right?
The API issue is real though thanks for pointing that out. I'll try to fix it asap.

`React.ReactNode` is a recursive type so it includes `React.ReactNodeArray` as well.

I'm open to changing it to `chunks` instead of `...chunks` but haven't really seen a whole lot of complaints about it. The `key` issue exists regardless. Changing between the 2 honestly isn't necessarily breaking since `React.ReactNode` is a recursive type as mentioned above. 

The point is that we return an arbitrary number of chunks which are reserved as implementation details. Having expectation on the number of chunks creates a lot of footguns from what I've seen in corporate usage. For example: devs expect to further transform some chunks with uppercase or such.

**Comment by czabaj** [comment] 2020-04-16 07:45
@longlho sorry, I will try to explain my thoughts more clearly.

There are currently two issues.

1. documentation
1. inconvenient API

## Documentation

As I said abov, there are currently 3 places where rich text messages are covered ([Components](@longlho sorry, I will try to explain my thoughts more clearly.

There are currently two issues.

1. documentation
1. inconvenient API

## Documentation

As I said abov, there are currently 3 places where rich text messages are covered (Components docs, [intl-messageformat](https://github.com/formatjs/formatjs/tree/master/packages/intl-messageformat#caveats) docs and imperative [API](https://github.com/formatjs/react-intl/blob/master/docs/API.md#formatmessage) docs). I propose to create comprehensive caveats of rich text messages in intl-messageformat and link to that from other Components and API. I tend to also change examples, so rest operators for arguments is used everywhere to express, that `formatXMLElementFn` can receive many chunks as variadic arguments and describe the cases, where this happens (nested rich texts, and maybe more?).

If you think this is OK, just give me thumbs up and I will prepare PR 😉 

## Inconvenient API

I opened separate issue for this #1623
