### ISSUE TITLE
Failed to minify the code from this file

### ISSUE THREAD

**Issue by zzsoszz** [formatjs/react-intl#1529] opened 2019-12-03 12:08 UTC
run yarn build getting errors.

command:
```
yarn build 
```

error:
```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/react-intl/lib/utils.js:29
```

### Environment
yarn  version  1.16.0
node version v10.16.0
npm  version 6.9.0
Windows_NT 6.1.7601

package.json
```json
{
  "name": "admin-frontend-mutilanguage",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "antd": "^3.24.3",
    "apollo-boost": "^0.1.9",
    "babel-plugin-styled-components": "^1.3.0",
    "decorate-component-with-props": "^1.1.0",
    "dom-to-image": "^2.6.0",
    "draft-js": "^0.10.4",
    "draft-js-plugins-editor": "^2.0.3",
    "draft-js-sticker-plugin": "^2.0.1",
    "express": "^4.17.1",
    "file-saver": "^2.0.2",
    "flat": "^5.0.0",
    "graphql": "0.13.0",
    "graphql-tag": "^2.9.2",
    "highlight.js": "^9.12.0",
    "html2canvas": "^1.0.0-rc.3",
    "jsonwebtoken": "^8.2.1",
    "jspdf": "^1.5.3",
    "jszip": "^3.2.1",
    "jwt-decode": "^2.2.0",
    "morgan": "^1.9.1",
    "node-uuid": "^1.4.8",
    "query-string": "5.1.1",
    "react": "16.8.6",
    "react-apollo": "^2.1.5",
    "react-app-rewire-styled-components": "^3.0.0",
    "react-codemirror": "^1.0.0",
    "react-codemirror2": "^3.0.7",
    "react-dom": "^16.2.0",
    "react-intl": "^3.9.1",
    "react-quill": "^1.2.3",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.0.17",
    "shortid": "^2.2.14",
    "sockjs-client": "^1.1.4",
    "stompjs": "^2.3.3",
    "styled-components": "^2.2.4",
    "worker-loader": "^2.0.0"
  },
  "scripts": {
    "start": "react-app-rewired start ",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test --env=jsdom",
    "eject": "react-scripts eject",
    "server": "node server-ssl.js"
  },
  "devDependencies": {
    "babel-plugin-import": "^1.6.2",
    "font-awesome": "^4.7.0",
    "marked": "^0.3.7",
    "react-app-rewire-less": "^2.1.0",
    "react-app-rewired": "^1.3.6"
  }
}

```

**Comment by longlho** [comment] 2019-12-03 14:39
dupe of #1499

**Closed by longlho** 2019-12-03 14:39 UTC
Labels: bug
