### ISSUE TITLE
Allow to load individual modules from react-intl

### ISSUE THREAD

**Issue by mschipperheyn** [formatjs/react-intl#906] opened 2017-03-16 15:49 UTC
React-intl is a pretty sizeable library. 

And we load its functionalities using `import { FormattedMessage, injectIntl } from 'react-intl';`

However, it seems that if you only need `FormattedMessage` and `intl.formatMessage`, a lot of unnecessary functionality is loaded. `intl-relativeFormat` for example, is loaded through a number of date formatting components. I don't use them, but I "pay" for it in download size.

I would recommend structuring react-intl so that you can import individual components. 
`import FormattedMessage from 'react-intl/lib/FormattedMessage';
`import injectIntl from 'react-intl/lib/injectIntl';

That way, webpack can easily eliminate unneeded code.

**Comment by ghostd** [comment] 2017-03-18 18:19
Is that a duplicate of your preivous issue #881?

**Comment by mschipperheyn** [comment] 2017-03-18 22:42
oops. You're right. closed the other

**Comment by timbset** [comment] 2019-02-15 13:11
Any news about that? I was shocked when bundle analyzer showed me that react-intl dependency contains all locales because of [this line](https://github.com/yahoo/react-intl/blob/master/src/index.js#L7). There is no legal way to fix it - only using your sources without warrantee of nothing changing after upgrade to the new version or using some webpack plugins that hardly cut it off. So here I see two good solutions:
1. Use structured components inside the lib like it is described above
2. Delete importing of all locales in the root (or explain me please why it is necessary when I can add all necessary for me locales on my side)

**Comment by neutraali** [comment] 2019-03-15 11:11
An unhandled `react-intl` (e.g. using `index`) with the required `intl-relativeformat` form a chunk of **1062.9kb (!!!)**.

This is pretty a pretty ridiculous amount of bloat to one's JS bundle.

**Comment by longlho** [comment] 2019-06-13 14:53
react-intl supports ESM now so I believe this is possible via tree-shaking.

**Closed by longlho** 2019-06-13 14:53 UTC
Labels: enhancement
