### ISSUE TITLE
'Malformed XML message' error when using '<' in message

### ISSUE THREAD

**Issue by matheusd** [formatjs/react-intl#1439] opened 2019-08-20 22:01 UTC
I'm upgrading to react-intl v3 (v3.1.10) and it seems the recent addition of rich text formatting broke strings with '<' in them.

I have the following component in my code:

```js
<FormattedMessage id="my-id" default-message="< 1 minute ago"/>
```

And I've started getting a "Malformed XML Error" in it. Here's a screenshot with the full error stack:
![image](https://user-images.githubusercontent.com/1752493/63387833-db0e0180-c37c-11e9-8271-037d11c234cf.png)

The string is displayed just fine but the error is annoying.

**Comment by longlho** [comment] 2019-08-21 02:57
thanks for reporting. Closing as duplicate of https://github.com/formatjs/formatjs/issues/148

**Closed by longlho** 2019-08-21 02:57 UTC
