### ISSUE TITLE
Text content did not match

### ISSUE THREAD

**Issue by kamilml** [formatjs/react-intl#1083] opened 2017-12-27 07:30 UTC
I am getting this ![chrome_2017-12-27_02-16-01](https://user-images.githubusercontent.com/20653004/34374064-ecfcbcce-eaac-11e7-82f4-2934101385d6.png)
when I use spanish language in my browser as my main language.

I am using nextjs and my custom wrapper component (hoc) is this:
```javascript
render () {
    return (
        <IntlProvider locale={ this.props.language } messages={ messages[this.props.language] }>
            <div>
                { '...' }
                <WrappedComp { ...this.props } />
            </div>
        </IntlProvider>
    )
}
```

This warning only happen with the `FormattedDate` component (with any config). I am using another like `FormattedMessage` normally.

And I checked the value of `this.props.language` in my server and browser render. Is always the same. `es` in my case.

**Comment by pbrandone** [comment] 2018-01-22 09:57
Same here.

Have you found the problem @kamilml ?

**Comment by keesvanlierop** [comment] 2018-03-13 16:14
I've notice translating texts work fine as locale is set properly, however `FormattedNumber` and `FormattedDate` don't work as expected. 

Could it be that node is missing something from the [Intl API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) that causes this issue?

**Comment by keesvanlierop** [comment] 2018-03-14 08:23
Fixed by polyfilling the Intl API in your server config. Recommended npm package: https://www.npmjs.com/package/intl

**Comment by EECOLOR** [comment] 2018-06-23 13:23
Could be caused by calling 'renderToStaticMarkup' instead of `renderToString` on the server for a component that is hydrated using `hydrate` in the browser.

**Closed** 2019-06-06 14:36 UTC
Labels: wontfix

**Comment by NooNoo1337** [comment] 2019-10-16 10:02
Still got this issue.  I took for example this project with polyfills to demonstrate an error: https://github.com/weiliang903/react-intl-with-next.

From SSR I'll get 'Wed, Oct 16' but on client side 'Wednesday, October 16'
