### ISSUE TITLE
3.x make WeChat browser crash in Android platform

### ISSUE THREAD

**Issue by Echo-Lynn** [formatjs/react-intl#1518] opened 2019-11-15 07:11 UTC
version:
react-intl v3.2.1
WeChat v7.0.8
Node.js v10.16.3

I switch react-intl version to v2.9.0 then it works normally in WeChat Browser

here is a picture showing this problem

![image](https://user-images.githubusercontent.com/56513397/68923873-533c6580-07ba-11ea-8cd5-5966a8672e6d.png)

**Comment by foubei** [comment] 2019-11-15 11:26
Duplicate of #1512

**Comment by Echo-Lynn** [comment] 2019-11-16 03:05
@longlho i think this is no the same with #1512 ，我check #1512 and found no solution to my problem

**Comment by longlho** [comment] 2019-11-16 03:21
Do you have a codesandbox.io repro case?

**Comment by Echo-Lynn** [comment] 2019-11-16 03:48
https://github.com/zeit/next.js/tree/master/examples/with-react-intl
Just run this demo on local server and use WeChat app scan to open the page you serve

**Comment by longlho** [comment] 2019-11-16 04:02
sorry I can't help u here bc I don't use WeChat

**Comment by gaijinjoe** [comment] 2019-11-26 06:14
Having a similar issue where WeChat browser is crashing. I suspect its caused by some missing polyfill. I've tried multiple polyfills: `Intl.NumberFormat`, `Intl.DateTimeFormat`, `Intl`, `Object.assign`, `Object.entities`, `Object.keys`. 

I've also tried using the babel.config.js (solution of #1512 ) with the following config: 
`module.exports = function(api) {
    console.log("👍 babel.config.js is being used")
    api.cache(true)
  
    const presets = [
      [
        "babel-preset-gatsby",
        {
          targets: {
            browsers: [">0%", "not dead"],
          },
        },
      ],
    ]
  
    const plugins = []
  
    return {
      presets,
      plugins,
    }
  }`

But it still doesn't work. If someone has a clue it would be appreciated.

**Comment by gaijinjoe** [comment] 2019-11-26 06:15
Having a similar issue where WeChat browser is crashing. I suspect its caused by some missing polyfill. I've tried multiple polyfills: `Intl.NumberFormat`, `Intl.DateTimeFormat`, `Intl`, `Object.assign`, `Object.entities`, `Object.keys`. 

I've also tried using the babel.config.js (solution of #1512 ) with the following config: 

` module.exports = function(api) {
    console.log("👍 babel.config.js is being used")
    api.cache(true)
  
    const presets = [
      [
        "babel-preset-gatsby",
        {
          targets: {
            browsers: [">0%", "not dead"],
          },
        },
      ],
    ]
  
    const plugins = []
  
    return {
      presets,
      plugins,
    }
  } `

But it still doesn't work. If someone has a clue it would be appreciated.

**Comment by gaijinjoe** [comment] 2019-11-26 06:16
Having a similar issue where WeChat browser is crashing. I suspect its caused by some missing polyfill. I've tried multiple polyfills: `Intl.NumberFormat`, `Intl.DateTimeFormat`, `Intl`, `Object.assign`, `Object.entities`, `Object.keys`. 

I've also tried using the babel.config.js (solution of #1512 ) with the following config: 

```
module.exports = function(api) {
    console.log("👍 babel.config.js is being used")
    api.cache(true)
  
    const presets = [
      [
        "babel-preset-gatsby",
        {
          targets: {
            browsers: [">0%", "not dead"],
          },
        },
      ],
    ]
  
    const plugins = []
  
    return {
      presets,
      plugins,
    }
  }
```

But it still doesn't work. If someone has a clue it would be appreciated.

**Comment by Echo-Lynn** [comment] 2019-11-26 06:39
@gaijinjoe Intl.NumberFormat().resolvedOptions() and new Intl.PluralRules() were called by  new version of formatjs source code, but X5 core broswer crash when everytime these two method executed. I already feedback this problem to the devolpers, and they will pushblish the fixed version in few days

**Closed** 2019-11-26 06:40 UTC

**Comment by Djiit** [comment] 2019-11-26 17:13
Hey @Echo-Lynn , thanks for the update. We are hitting the same bug. Can you point us to the place you gave the feedback to the X5 Core browser day so we can follow it ? Thanks 🙏

**Comment by longlho** [comment] 2019-11-26 17:17
We also recently released a fix on our side for `intl-unified-numberformat) so if you guys can update your packages and lmk if it's still broken (just to rule out that part)

**Comment by Echo-Lynn** [comment] 2019-11-26 17:32
@Djiit You can feedback any problem you met in X5 core broswer here: https://x5.tencent.com/tbs/feedback.html

**Comment by gaijinjoe** [comment] 2019-11-26 18:25
@longlho everything updated and still the same issue.

**Comment by longlho** [comment] 2019-11-26 18:26
ok then looks like it's a browser issue then.

**Comment by gaijinjoe** [comment] 2019-11-27 17:56
@Echo-Lynn can you update us when the X5 core browser is updated and this is fixed please?

**Comment by yuanzhhh** [comment] 2019-11-29 12:58
I also encountered the same problem. WeChat

config version:
"react-intl": "^3.3.2",
"webpack": "^4.41.2",
"typescript": "^3.7.2",
"@babel/core": "^7.7.0",
"@babel/plugin-transform-runtime": "^7.6.2",
"@babel/runtime": "^7.7.4",

React-intl make WeChat browser crash in Android.

**Comment by foubei** [comment] 2019-12-01 03:03
The only fix for now is to downgrade to **react-intl 2.x.x** at least in my side :(

**Comment by gaijinjoe** [comment] 2019-12-01 11:48
Downgrading to 2.9.0 actually works for me too. I tried everything to make it work with 3.x.x with no success. Therefore I believe this issue should be re-opened since it's caused by the latest versions of react-intl.

**Comment by longlho** [comment] 2019-12-01 12:37
Latest version of react-intl uses newer Intl API and there’re polyfills
expected for them. Given that major browsers don’t crash this is not our
issue.
