### ISSUE TITLE
react-intl doesnt work with typescript

### ISSUE THREAD

**Issue by AndrewMerke** [formatjs/react-intl#1256] opened 2019-03-20 12:06 UTC
I have a problem to set up react-intl with react typescript project. I tried two ways to set up everything and always getting error:

```
TS2605: JSX element type 'IntlProvider' is not a constructor function for JSX elements.
  Property 'render' is missing in type 'IntlProvider'.
```

For example I am trying to implement it like this:

 ```
  import { IntlProvider, addLocaleData } from 'react-intl';
   
   const locale = 'fr';
   // load our messages
   const messages = require('./translations/locales/fr.json');
   // get the French locale information from the browser
   import fr = require('react-intl/locale-data/fr');
   addLocaleData(fr);
      
   ReactDOM.render(
       <IntlProvider locale={locale} messages={messages} key={locale}>
           <App />
       </IntlProvider>,
       document.getElementById('root') as HTMLElement
   );
```

Versions:
"@types/react-intl": "^2.3.17",
"react-intl": "^2.8.0"

Maybe anyone had same problem?

**Comment by oriSomething** [comment] 2019-03-20 16:29
What is the TypeScript version? for me it works perfectly

**Comment by AndrewMerke** [comment] 2019-03-21 12:14
@oriSomething, 3.3.3

**Comment by redonkulus** [comment] 2019-05-15 04:52
@AndrewMerke Can you try version 3.4.5 just to be safe?

**Comment by erickskrauch** [comment] 2019-05-18 22:48
@AndrewMerke can confirm the same behavior with TS 3.4.5 and latests `react 16.8.17`, `react-dom 16.8.4`, `react-intl 2.3.17` typings:

<details><summary>yarn tsc</summary><p>

```bash
erickskrauch@home ~/w/elyby-email-renderer> yarn tsc
yarn run v1.16.0
$ /home/erickskrauch/www/elyby-email-renderer/node_modules/.bin/tsc
src/App.tsx:30:9 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

30         <IntlProvider locale={locale} messages={messages}>
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/App.tsx:30:10 - error TS2322: Type '{ children: Element; locale: string; messages: any; }' is not assignable to type '{}'.
  Property 'children' does not exist on type '{}'.

30         <IntlProvider locale={locale} messages={messages}>
            ~~~~~~~~~~~~

src/components/blocks/code/Code.tsx:26:13 - error TS2605: JSX element type 'FormattedMessage' is not a constructor function for JSX elements.
  Type 'FormattedMessage' is missing the following properties from type 'ElementClass': render, context, setState, forceUpdate, and 3 more.

26             <Message {...messages.or} />
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/blocks/code/Code.tsx:26:13 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

26             <Message {...messages.or} />
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/blocks/code/Code.tsx:29:13 - error TS2605: JSX element type 'FormattedMessage' is not a constructor function for JSX elements.

29             <Message {...messages.pass_code_in_field} />
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/blocks/code/Code.tsx:29:13 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

29             <Message {...messages.pass_code_in_field} />
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/layout/footer/Footer.tsx:15:21 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

 15                     <Message {...messages.footer} values={{
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 16                         serviceLink:
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 19                             </a>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 20                     }} />
    ~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/layout/footer/Footer.tsx:15:22 - error TS2322: Type '{ values: { serviceLink: Element; }; id: string; defaultMessage: string; }' is not assignable to type '{}'.
  Property 'values' does not exist on type '{}'.

15                     <Message {...messages.footer} values={{
                        ~~~~~~~

src/components/layout/footer/Footer.tsx:18:33 - error TS2605: JSX element type 'FormattedMessage' is not a constructor function for JSX elements.

18                                 <Message {...messages.service_name} />
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/layout/footer/Footer.tsx:18:33 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

18                                 <Message {...messages.service_name} />
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/layout/footer/Footer.tsx:25:25 - error TS2605: JSX element type 'FormattedHTMLMessage' is not a constructor function for JSX elements.
  Type 'FormattedHTMLMessage' is missing the following properties from type 'ElementClass': render, context, setState, forceUpdate, and 3 more.

25                         <HTMLMessage {...messages.alternativeMinecraftServices} />
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/layout/footer/Footer.tsx:25:25 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

25                         <HTMLMessage {...messages.alternativeMinecraftServices} />
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/layout/header/Header.tsx:19:21 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

19                     <Message {...messages.hello_username} values={{username}} />
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/layout/header/Header.tsx:19:22 - error TS2322: Type '{ values: { username: string; }; id: string; defaultMessage: string; }' is not assignable to type '{}'.
  Property 'values' does not exist on type '{}'.

19                     <Message {...messages.hello_username} values={{username}} />
                        ~~~~~~~

src/emails/forgotPassword/ForgotPassword.tsx:22:13 - error TS2605: JSX element type 'FormattedHTMLMessage' is not a constructor function for JSX elements.

22             <HTMLMessage {...messages.forgot_the_password_image}/>
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/forgotPassword/ForgotPassword.tsx:22:13 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

22             <HTMLMessage {...messages.forgot_the_password_image}/>
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/forgotPassword/ForgotPassword.tsx:30:29 - error TS2605: JSX element type 'FormattedMessage' is not a constructor function for JSX elements.

30                             <Message {...messages.shit_happens} />
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/forgotPassword/ForgotPassword.tsx:30:29 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

30                             <Message {...messages.shit_happens} />
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/forgotPassword/ForgotPassword.tsx:37:29 - error TS2605: JSX element type 'FormattedHTMLMessage' is not a constructor function for JSX elements.

37                             <HTMLMessage {...messages.continue_image} />
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/forgotPassword/ForgotPassword.tsx:37:29 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

37                             <HTMLMessage {...messages.continue_image} />
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:26:13 - error TS2605: JSX element type 'FormattedHTMLMessage' is not a constructor function for JSX elements.

26             <HTMLMessage {...messages.welcome_image} />
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:26:13 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

26             <HTMLMessage {...messages.welcome_image} />
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:34:29 - error TS2605: JSX element type 'FormattedMessage' is not a constructor function for JSX elements.

34                             <Message {...messages.we_glad_to_see_you} />
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:34:29 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

34                             <Message {...messages.we_glad_to_see_you} />
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:41:29 - error TS2605: JSX element type 'FormattedHTMLMessage' is not a constructor function for JSX elements.

41                             <HTMLMessage {...messages.confirm_email_image} />
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:41:29 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

41                             <HTMLMessage {...messages.confirm_email_image} />
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:50:25 - error TS2605: JSX element type 'FormattedHTMLMessage' is not a constructor function for JSX elements.

50                         <HTMLMessage {...messages.whats_next_image} />
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:50:25 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

50                         <HTMLMessage {...messages.whats_next_image} />
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:61:37 - error TS2605: JSX element type 'FormattedHTMLMessage' is not a constructor function for JSX elements.

61                                     <HTMLMessage {...messages.choose_you_skin_image} />
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:61:37 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

61                                     <HTMLMessage {...messages.choose_you_skin_image} />
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:66:41 - error TS2605: JSX element type 'FormattedMessage' is not a constructor function for JSX elements.

66                                         <Message {...messages.choose_you_skin_text} />
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:66:41 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

66                                         <Message {...messages.choose_you_skin_text} />
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:81:37 - error TS2605: JSX element type 'FormattedHTMLMessage' is not a constructor function for JSX elements.

81                                     <HTMLMessage {...messages.install_our_patch_image} />
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:81:37 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

81                                     <HTMLMessage {...messages.install_our_patch_image} />
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:86:41 - error TS2605: JSX element type 'FormattedMessage' is not a constructor function for JSX elements.

86                                         <Message {...messages.install_our_patch_text} />
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:86:41 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

86                                         <Message {...messages.install_our_patch_text} />
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:101:37 - error TS2605: JSX element type 'FormattedHTMLMessage' is not a constructor function for JSX elements.

101                                     <HTMLMessage {...messages.useTLLauncher} />
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:101:37 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

101                                     <HTMLMessage {...messages.useTLLauncher} />
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:106:41 - error TS2605: JSX element type 'FormattedMessage' is not a constructor function for JSX elements.

106                                         <Message {...messages.useTLLauncherText} />
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/emails/register/Register.tsx:106:41 - error TS2607: JSX element class does not support attributes because it does not have a 'props' property.

106                                         <Message {...messages.useTLLauncherText} />
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 40 errors.

error Command failed with exit code 1.
```

</p></details>

I would be happy to provide any additional information.

**Comment by redonkulus** [comment] 2019-05-30 13:16
@erickskrauch is it possible this is an issue with the type definition? I haven't used TS with this project so I'm not sure if its a bug with the definition or something else.

**Comment by erickskrauch** [comment] 2019-06-03 15:05
@redonkulus yes, it's an issue of type definition or whole TypeScript. I managed to find out that the problem was caused by `require` statement in the root `index.ts` file:

```js
const React = require('react');
```

**Comment by longlho** [comment] 2019-06-06 23:39
closing in favor of #1306

**Closed by longlho** 2019-06-06 23:39 UTC
Labels: needs info
