### ISSUE TITLE
component don't re-render when changing locale

### ISSUE THREAD

**Issue by FatehDzIt** [formatjs/react-intl#1510] opened 2019-11-09 10:23 UTC
## Description

 after setting react intl and locale state in redux i made some drop-down to switch between locales,
it works and the state is changing correctly in redux but them component don't re-render i have to reload to make it work

### Expected behavior

component should re-render after changing locale

### Current behavior

i have to reload the page to apply locale change

### Step to reproduce for BUG REPORT
```javascript
ReactDOM.render(
<Provider store={store}>
    <IntlProvider locale={lang} messages={messages[lang]}>
        <SnackbarProvider
             maxSnack={1}
              anchorOrigin={{ vertical: "top", horizontal: "center" }}
              preventDuplicate
          >`
              <App />
         </SnackbarProvider>
    </IntlProvider>
</Provider>
 document.getElementById("root")
);
```

### Environment

|          Executable | Version |
| ------------------: | :------ |
| `react-intl` | 3.4.0|
|      `react` | 16.11.0|
|     `react-dom` | 16.11.0|
|     `redux` | 4.0.4|
|     `material-ui` | 4.5.1|
|    `node --version` | 12.13.0|

| OS   | Version |
| ---- | ------- |
| Windows 10| 1803|

| Browser | Version |
| ------- | ------- |
| Chrome| 78.0.3904.97 |

**Comment by longlho** [comment] 2019-11-10 03:22
Do you have a codesandbox.io demo?

**Comment by FatehDzIt** [comment] 2019-11-11 16:14
https://codesandbox.io/s/floral-flower-xewr0?fontsize=14

**Comment by longlho** [comment] 2019-11-11 16:20
The issue is because `locale` var was hoisted out of scope so it never changes even though you change it in the store. Fix: https://codesandbox.io/s/react-intlrenderissue-7xnlf

**Closed by longlho** 2019-11-11 16:20 UTC

**Comment by FatehDzIt** [comment] 2019-11-11 16:36
thank you for your help bro
