### ISSUE TITLE
Formatting with a child component doesn't resolve placeholders

### ISSUE THREAD

**Issue by ahjmorton** [formatjs/react-intl#1138] opened 2018-06-18 17:18 UTC
### Expected behaviour
When formatting and passing the text for a child component I would expect that the placeholders in the string get resolved before receiving the string.

### Current behavior
~The placeholder is not resolved and the label itself is passed in but the placeholder is just blank.~
Turns out that the placeholder is resolved and it passed as a separate argument to the function so in the case below the function signature is actually ```(label, link) => // <p>{label} {link}```.

### Step to reproduce 
Assuming the translations are as follows :
```
label=Please click {link} 
link=On this link
```

```
<FormattedMessage
    id="label" 
    values={{link: (<a href="www.google.co.uk"><FormattedMessage id="link" /></a>)}}
 > {text => // This would be more complicated IRL
    <p>{text}</p>
}</FormattedMessage> `
```
Will give you back
```
Please click
```
### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.4.0 |
| `npm ls react` | 16.2.0 |
| `npm --version` | 5.6.0 |
| `node --version` | v8.4.0 |

| OS | Version |
| --- | --- |
| Ubuntu | 16.04 |

| Browser | Version |
| --- | --- |
| Chromium | 66.0.3359.181 |

**Comment by papasmile** [comment] 2018-06-23 17:16
Looks like a duplicate of #1131 and related to #513.

**Closed** 2019-05-30 04:59 UTC
