### ISSUE TITLE
components/tags usage in ICU

### ISSUE THREAD

**Issue by ValeryVS** [formatjs/react-intl#1377] opened 2019-07-23 11:53 UTC
I want to use components inside strings that will be translated.

In angular and some other react libraries, components could be mixed in extracted strings like `<0>a<1>b</1>c</0><2>3</2>`. I wonder why `react-intl` doesn't cover this.

Why not to make it something like this?
```tsx
<FormattedMessage
  id="welcome"
  defaultMessage={`{unreadCount, plural,
    one {Hello <0>{name}</0>, you have <1>{unreadCount, number} message</1>}
    other {Hello <0>{name}</0>, you have <1>{unreadCount, number} messages</1>}
  }`}
  components={[<ProfileLink />, <MessagesLink />]}
  values={{name, unreadCount}}
/>
```
or with components
```tsx
<FormattedMessage
  id="welcome"
>
  Hello <ProfileLink>{name}</ProfileLink>, you have <MessagesLink><FormattedNumber value={unreadCount} /> <FormattedPlural value={unreadCount} one={'message'} other={'messages'} /></MessagesLink></>}
</FormattedMessage>

<FormattedPlural
  value={unreadCount}
  one={<>Hello <ProfileLink>{name}</ProfileLink>, you have <MessagesLink><FormattedNumber value={unreadCount} /> message</MessagesLink></>}
  other={<>Hello <ProfileLink>{name}</ProfileLink>, you have <MessagesLink><FormattedNumber value={unreadCount} /> messages</MessagesLink></>}
/>
```

**Comment by DragonRaider5** [comment] 2019-07-23 13:08
Why not use

```js
<FormattedMessage
  id="welcome"
  defaultMessage={`{unreadCount, plural,
    one {Hello <0>{name}</0>, you have {unreadMessages}}
    other {Hello <0>{name}</0>, you have {unreadMessages}}
  }`} // for english this isn't reasonable, might be for other languages
  values={{
    name: <ProfileLink name={name} />,
    unreadCount,
    unreadMessages: <UnreadCount count={unreadCount} />
  }}
/>
```

**Comment by longlho** [comment] 2019-07-23 13:19
we've talked about supporting it for a while but haven't got time. `<0>foo</0` does provide a better context for translators

**Comment by ValeryVS** [comment] 2019-07-23 14:09
@DragonRaider5 
In your example word "messages" will be in separate component `UnreadCount`.
Translators will see strings "you have..." and "{count, number} messages" separately. And well ask you, developer, what exactly `{unreadMessages}` is.
Because it can be "未読メッセージが5通あります" for example.
Which equivalent to "unread messages 5 items there is".

Using separate components with part of sentence can be bad way for internationalization, because, when such component is reusable in English, it can be not reusable in some other languages.

**Comment by DragonRaider5** [comment] 2019-07-23 14:23
`{unreadMessages}` would be a plural rule and also done by the translators.
It then can be hinted at in the respective field of `defineMessages(...)`.

**Comment by longlho** [comment] 2019-07-23 18:21
dupe of #513

**Closed by longlho** 2019-07-23 18:21 UTC
Labels: enhancement
