### ISSUE TITLE
Abbreviated numbers (enhancement)

### ISSUE THREAD

**Issue by doublex** [formatjs/react-intl#1144] opened 2018-06-26 20:31 UTC
CLDR supports in "numbers" -&gt; "decimalFormats" -&gt; "decimalFormat" abbreviated numbers, .e.g.:
3150 -> "3k"
700000000 -> "700M"
Would be a great enhancement.

**Comment by papasmile** [comment] 2018-06-28 15:11
Hi, @doublex can you point to a link on http://cldr.unicode.org or somewhere else that describes that spec?  Looked around a bit and couldn't find it there.

Also, React Intl just uses Int.NumberFormat for formatting numbers:
https://github.com/yahoo/react-intl/wiki/API#formatnumber
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

**Comment by doublex** [comment] 2018-06-28 16:16
Maybe this?
http://cldr.unicode.org/translation/number-patterns
The data is in CLDR "main" repository.

**Comment by nicholasodonnell** [comment] 2018-07-25 19:16
I would really love to see this feature. Is there any update for this?

**Comment by papasmile** [comment] 2018-07-26 03:40
thx, @doublex that's it.  also for reference e.g. en-US short number CLDR values: https://github.com/unicode-cldr/cldr-numbers-full/blob/33.0.0/main/en-US-POSIX/numbers.json#L63-L89

**Comment by longlho** [comment] 2019-06-06 23:40
duplicate of #479

**Closed by longlho** 2019-06-06 23:40 UTC
Labels: enhancement
