### ISSUE TITLE
Missing locale data for locale: "ru". Using default locale: "en" as fallback.

### ISSUE THREAD

**Issue by maystrenkoYurii** [formatjs/react-intl#1587] opened 2020-02-19 19:56 UTC
Error on server using server side rendering. Client not have some error.
![Снимок экрана от 2020-02-19 21-54-27](https://user-images.githubusercontent.com/23016311/74870564-9fbbb200-5362-11ea-8064-1675cac123cb.png)

**Comment by mkholjuraev** [comment] 2020-02-20 15:00
We are having the same issue

**Comment by longlho** [comment] 2020-02-20 15:03
Your Node needs to have full-icu so either node 13+ or you have to use the
full-icu package. Please refer to our docs for more details

**Comment by DragonRaider5** [comment] 2020-03-04 15:28
@maystrenkoYurii @mkholjuraev did this solve your issue? If so please close this issue.
If not please provide additional information.

**Comment by mkholjuraev** [comment] 2020-03-05 08:43
I am sorry, but it did not solve my issue. I can not use intl.formatMessage(messages.vectorNamesV3AV) API after configuring the Intl. The problem is formatMessage is using default locale instead of translated locale in a non react file (in my constants file).
This is how I configured the Intl:

```
import { createIntl, createIntlCache } from 'react-intl';
import messages from '../../../Messages';

const cache = createIntlCache();
const locale = navigator.language;
const intl = createIntl({
    // eslint-disable-next-line no-console
    onError: console.log,
    locale
}, cache);
```
If I am doing something incorrect please feel free to make a comment.

**Comment by DragonRaider5** [comment] 2020-03-05 10:01
Hey @mkholjuraev ,

Thanks for your response. To use the `int.formatMessages(...)` API you'll have to pass an object of your translated messages to your call of `createIntl({ ...others, messages })`.

If you have already done so, could you provide us with your call to `intl.formatMessage(...)` and double check the key exists on your messages object?

@longlho is this also the message you get when not providing the message, or am I mistaking?

**Comment by DragonRaider5** [comment] 2020-03-05 10:07
@mkholjuraev could you also provide us with the output of `node -v` and `npm ls full-icu` when executed in your project root?

**Comment by mkholjuraev** [comment] 2020-03-05 12:55
Thank you, it did solve my issue. Sorry for my mistake. You helped me a lot.

**Comment by longlho** [comment] 2020-03-05 15:09
Thanks a lot for the help @DragonRaider5

**Closed by longlho** 2020-03-05 15:09 UTC
Labels: question
